name: Deploy to AWS

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to AWS
      id: login-ecr
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/o7n0b9d2

    - name: Build, tag, and push image to AWS
      id: build-and-push-image
      run: |
        docker build -t github-actions-smarthack .
        docker tag github-actions-smarthack:latest public.ecr.aws/o7n0b9d2/github-actions-smarthack:latest
        docker push public.ecr.aws/o7n0b9d2/github-actions-smarthack:latest

    - name: Restart task
      id: restart-task
      run: |
        x=(aws ecs list-tasks --cluster ${{ secrets.AWS_CLUSTER }} --output text --query taskArns[0])
        echo $x
        aws ecs stop-task --task $x --cluster ${{ secrets.AWS_CLUSTER }}
